name: dev

on: 
  workflow_dispatch:

    
jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # - name: Azure Login
      #  uses: azure/login@v1
      #  with:
      #    creds: ${{ secrets.AZURE_AD_SUBS_LEVEL }}
      
      - name: Checkout
        uses: actions/checkout@v1

      - name: AzCli
        uses: azure/cli@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az sql server create -n essilordevserverrebo -g rg-4pc-dev -l eastus2 -u ${{ secrets.AZURE_SQL_SERVER_USERNAME }} -p ${{ secrets.AZURE_SQL_SERVER_PASSWORD }}
          
      
