name: dev

on: 
  workflow_dispatch:

    
jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_AD_SUBS_LEVEL }}
            
      - name: Checkout
        uses: actions/checkout@v1

      - name: Az CLI
        run: |
          param="testing"
          chmod +x $GITHUB_WORKSPACE/deploy/CreateResources.sh
          $GITHUB_WORKSPACE/deploy/CreateResources.sh
        #  $GITHUB_WORKSPACE/deploy/CreateResources.sh "${param}""
        # uses: azure/cli@v1
        # with:
        #   azcliversion: 2.30.0
        #   inlineScript: |
        #     param="test params"
        #     echo $params
        #     chmod +x $GITHUB_WORKSPACE/deploy/CreateResources.sh "${param}"
        #     $GITHUB_WORKSPACE/deploy/CreateResources.sh "${param}"
      - name: az logout
        run: |
          az logout

          
      
