name: dev

on: 
  workflow_dispatch:

    
jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # - name: Azure Login
      #  uses: azure/login@v1
      #  with:
      #    creds: ${{ secrets.AZURE_AD_SUBS_LEVEL }}
      - name: Azure Login
        uses: azure/cli@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az login -u ${{ secrets.AZURE_AD_USERNAME }} -p ${{ secrets.AZURE_AD_PASSWORD }}
            
      - name: Checkout
        uses: actions/checkout@v1

      - name: AzCli
        uses: azure/cli@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            param="test params"
            chmod +x $GITHUB_WORKSPACE/deploy/CreateResources.sh "${param}"
            $GITHUB_WORKSPACE/deploy/CreateResources.sh "${param}"
          
      
