name: dev

on: 
  workflow_dispatch:

    
jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_AD_SUBS_LEVEL }}
            
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set env to dev
        if: github.ref == 'refs/heads/main'
        run: |
          echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          echo "SQLSERVERPASSWORD=${{ secrets.AZURE_SQL_SERVER_PASSWORD }}" >> $GITHUB_ENV
          echo "SQLSERVERUSERNAME=${{ secrets.AZURE_SQL_SERVER_USERNAME }}" >> $GITHUB_ENV

      - name: echo ref and env
        run: |
          echo "the ref is: $GITHUB_REF"
          echo "the env is: $ENVIRONMENT"
          echo "SQL Server Username: $SQLSERVERUSERNAME"
          echo "SQL Server Password: $SQLSERVERPASSWORD"

      - name: Az CLI
        uses: azure/cli@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/deploy/$ENVIRONMENT/CreateResources.sh
            $GITHUB_WORKSPACE/deploy/$ENVIRONMENT/CreateResources.sh

      - name: Az CLI - AKS and ACR
        uses: azure/cli@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/deploy/$ENVIRONMENT/Aks.sh
            $GITHUB_WORKSPACE/deploy/$ENVIRONMENT/Aks.sh
            
      - name: az logout
        run: |
          az logout

          
      
